name    'alkivi-mysql'
version '0.0.2'
source 'https://github.com/alkivi/puppet-mysql'
author 'alkivi'
license 'LGPLv3'
summary 'Control MySQL server and allow database/user creation'
description 'Setup MySQL server and give puppet type for database user creation'
project_page 'https://github.com/alkivi/puppet-mysql'
dependency 'puppetlabs/stdlib', '>3.x'
#dependency 'puppetlabs/concat', '1.0.0'
dependency 'alkivi/alkivi_base', '>0.x'
